In [2]:
import numpy as np 

In [3]:
arr1 = np.arange(24).reshape(6,4)

In [4]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [9]:
arr1[[2,3,5]]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [20, 21, 22, 23]])

In [14]:
arr1[:1,:3]

array([[0, 1, 2]])