In [3]:
import numpy as np

In [7]:
arr= np.random.randint(low=0,high=100,size=20).reshape(4,5)

In [11]:
arr[arr>50]

array([86, 64, 99, 69, 82, 69, 56, 92])

In [14]:
arr>50

array([[False, False, False,  True,  True],
       [ True,  True, False,  True, False],
       [False, False, False,  True, False],
       [False,  True, False, False,  True]])

In [20]:
arr[(arr>50) & (arr%2==0)]

array([86, 64, 82, 56, 92])

In [22]:
arr1=arr[(arr>50) & (arr%2==0)]


In [24]:
arr1

array([86, 64, 82, 56, 92])

In [29]:
arr[(arr>50) & (arr%2==0)]=0

In [30]:
arr

array([[17,  4, 49,  0,  0],
       [99, 69, 43,  0, 47],
       [22, 25, 16, 69, 29],
       [47,  0, 16, 31,  0]])