In [2]:
import numpy as np

In [6]:
arr1 = np.arange(12).reshape(3,4)

In [8]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr1.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
arr1.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [14]:
arr2 = np.arange(12,24).reshape(3,4)

In [16]:
arr2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [31]:
arr3=arr1.reshape(3,4)

In [33]:
np.hstack((arr3,arr2))

array([[12, 13, 14, 15, 12, 13, 14, 15],
       [16, 17, 18, 19, 16, 17, 18, 19],
       [20, 21, 22, 23, 20, 21, 22, 23]])

In [35]:
np.vstack((arr2,arr3))

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
np.hsplit(arr3,4)

[array([[12],
        [16],
        [20]]),
 array([[13],
        [17],
        [21]]),
 array([[14],
        [18],
        [22]]),
 array([[15],
        [19],
        [23]])]

In [41]:
np.vsplit(arr3,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [49]:
arr5= np.array([ [ [1,3,2] ,[1,4,5] ],[[1,2,3 ],[1,2,3]]])

In [50]:
arr5

array([[[1, 3, 2],
        [1, 4, 5]],

       [[1, 2, 3],
        [1, 2, 3]]])